/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
#include "JniTools.h"
/* Header for class com_xyz_nio_channels_Selector */

#ifndef _Included_com_xyz_nio_channels_Selector
#define _Included_com_xyz_nio_channels_Selector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xyz_nio_channels_Selector
 * Method:    open
 * Signature: ()Lcom/xyz/nio/channels/Selector;
 */
JNIEXPORT jobject JNICALL Java_com_xyz_nio_channels_Selector_open
  (JNIEnv *, jclass);

/*
 * Class:     com_xyz_nio_channels_Selector
 * Method:    select
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xyz_nio_channels_Selector_select
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
