/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
#include "JniTools.h"
/* Header for class com_xyz_nio_channels_SocketChannel */

#ifndef _Included_com_xyz_nio_channels_SocketChannel
#define _Included_com_xyz_nio_channels_SocketChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_xyz_nio_channels_SocketChannel
* Method:    configureBlocking
* Signature: (Z)Lcom/xyz/nio/channels/SocketChannel;
*/
JNIEXPORT jobject JNICALL Java_com_xyz_nio_channels_SocketChannel_configureBlocking
        (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_xyz_nio_channels_SocketChannel
 * Method:    register0
 * Signature: (Lcom/xyz/nio/channels/Selector;I)Lcom/xyz/nio/channels/SelectionKey;
 */
JNIEXPORT jobject JNICALL Java_com_xyz_nio_channels_SocketChannel_register0
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_xyz_nio_channels_SocketChannel
 * Method:    read0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_xyz_nio_channels_SocketChannel_read0
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
